hfh4-zephyr-7b-g-dpo:
  prompt_template: "./alpaca_eval/models_configs/HuggingFaceH4/zephyr-7b-g-dpo/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "HuggingFaceH4/zephyr-7b-gemma-v0.1"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 1024
    temperature: 0.7
    top_p: 1.0
    batch_size: 64
    do_sample: True
  pretty_name: "Gemma 7B Zephyr SFT"

